# Generated by Django 6.0.5 on 2026-05-28 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('download', 'Download'), ('permission_denied', 'Permission Denied'), ('failed_login', 'Failed Login')], max_length=50)),
                ('resource', models.CharField(help_text='Model name (User, Booking, Car, etc)', max_length=100)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('http_method', models.CharField(blank=True, max_length=10)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='api_auditlo_user_id_8f69e8_idx'), models.Index(fields=['action', 'timestamp'], name='api_auditlo_action_070bba_idx'), models.Index(fields=['resource', 'timestamp'], name='api_auditlo_resourc_2dc76f_idx'), models.Index(fields=['ip_address', 'timestamp'], name='api_auditlo_ip_addr_f9c369_idx')],
            },
        ),
    ]
