# Generated by Django 6.0.5 on 2026-05-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên xe (VD: Toyota Vios 2023)', max_length=100)),
                ('license_plate', models.CharField(help_text='Biển số xe', max_length=20, unique=True)),
                ('vehicle_type', models.CharField(help_text='Loại xe (Sedan, SUV, Van, etc)', max_length=50)),
                ('latitude', models.FloatField(default=10.7769, help_text='Vĩ độ')),
                ('longitude', models.FloatField(default=106.6966, help_text='Kinh độ')),
                ('location_name', models.CharField(blank=True, help_text='Tên địa điểm', max_length=255)),
                ('status', models.CharField(choices=[('available', 'Còn trống'), ('rented', 'Đang cho thuê'), ('maintenance', 'Bảo trì'), ('inactive', 'Không hoạt động')], default='available', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_location_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['name'],
            },
        ),
    ]
